### PR TITLE
Add demo and anonymous modes

### PR DESCRIPTION
**Pull request by evilpegasus**

### CODE REVIEW

**Comment by evilpegasus** [comment]
The 3rd party authentication is not loading on the landing page.

**Comment by evilpegasus** [comment]
Going to the about and FAQ pages still kicks demo users back to the login screen

**Comment by arnavthareja** [comment]
The Welcome/Instructions popup automatically closes in demo and anonymous modes once the old image is drawn to the canvas

**Comment by arnavthareja** [comment]
> Going to the about and FAQ pages still kicks demo users back to the login screen

Fixed in b031ece67400c8bf436daa71eb97e727f3502018

**Comment by arnavthareja** [comment]
> The Welcome/Instructions popup automatically closes in demo and anonymous modes once the old image is drawn to the canvas
> 
> The popup automatically reopens once another popup is shown

Fixed in f11c2497886dfa64a73021618ab71bb8afbb2574

**Pull request merged**
